[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"
# keywords = []
# categories = []

[dependencies]

[dev-dependencies]
criterion = "0.5"
pretty_assertions = "1.4"
