#!/usr/bin/env just --justfile
set dotenv-load := true

# interactive menu by default
default:
  @just --choose

# outputs list of tasks
list:
  @just --list

# apply strict formatting
fmt *FLAGS:
  cargo +nightly fmt --all {% raw %}{{FLAGS}}{% endraw %}

# run test suite
test *FLAGS:
  cargo nextest run --all-features --workspace {% raw %}{{FLAGS}}{% endraw %}

# generate documentation
doc:
  mdbook build

# setup dev environment
init:
  echo # installing nightly used by `just fmt` and `cargo udeps`
  rustup install nightly

  echo # installing cargo-binstall for faster setup time
  cargo binstall -V || cargo install cargo-binstall

  echo # requirements for `just test`
  cargo binstall cargo-nextest --no-confirm

  echo # requirements for `just doc`
  cargo binstall mdbook --no-confirm
